import { ComponentSettingsSchema } from '@/lib/settings-types';

export const classicButtonSettingsSchema: ComponentSettingsSchema = {
    componentId: 'classic-button',
    fields: [
        // Content
        {
            id: 'text',
            type: 'text',
            label: 'Button Text',
            group: 'content',
            default: 'Click Me',
            placeholder: 'Enter button text...',
            maxLength: 30,
        },

        // Style
        {
            id: 'backgroundColor',
            type: 'color',
            label: 'Background Color',
            group: 'style',
            default: '#ffffff',
        },
        {
            id: 'textColor',
            type: 'color',
            label: 'Text Color',
            group: 'style',
            default: '#0a0a0a',
        },
        {
            id: 'hoverColor',
            type: 'color',
            label: 'Hover Color',
            description: 'Background color on hover',
            group: 'style',
            default: '#e5e5e5',
        },
        {
            id: 'borderRadius',
            type: 'slider',
            label: 'Border Radius',
            group: 'style',
            default: 8,
            min: 0,
            max: 50,
            step: 2,
            unit: 'px',
        },
        {
            id: 'paddingX',
            type: 'slider',
            label: 'Horizontal Padding',
            group: 'style',
            default: 20,
            min: 8,
            max: 48,
            step: 4,
            unit: 'px',
        },
        {
            id: 'paddingY',
            type: 'slider',
            label: 'Vertical Padding',
            group: 'style',
            default: 10,
            min: 4,
            max: 24,
            step: 2,
            unit: 'px',
        },
        {
            id: 'fontWeight',
            type: 'select',
            label: 'Font Weight',
            group: 'style',
            default: '500',
            options: [
                { value: '400', label: 'Regular' },
                { value: '500', label: 'Medium' },
                { value: '600', label: 'Semibold' },
                { value: '700', label: 'Bold' },
            ],
        },

        // Advanced
        {
            id: 'showBorder',
            type: 'toggle',
            label: 'Show Border',
            group: 'advanced',
            default: false,
        },
        {
            id: 'borderColor',
            type: 'color',
            label: 'Border Color',
            group: 'advanced',
            default: '#262626',
        },
    ],
};

export const outlineButtonSettingsSchema: ComponentSettingsSchema = {
    componentId: 'outline-button',
    fields: [
        {
            id: 'text',
            type: 'text',
            label: 'Button Text',
            group: 'content',
            default: 'Learn More',
            maxLength: 30,
        },
        {
            id: 'borderColor',
            type: 'color',
            label: 'Border Color',
            group: 'style',
            default: '#404040',
        },
        {
            id: 'textColor',
            type: 'color',
            label: 'Text Color',
            group: 'style',
            default: '#ffffff',
        },
        {
            id: 'hoverBackgroundColor',
            type: 'color',
            label: 'Hover Background',
            group: 'style',
            default: '#1a1a1a',
        },
        {
            id: 'borderRadius',
            type: 'slider',
            label: 'Border Radius',
            group: 'style',
            default: 8,
            min: 0,
            max: 50,
            step: 2,
            unit: 'px',
        },
        {
            id: 'borderWidth',
            type: 'slider',
            label: 'Border Width',
            group: 'style',
            default: 1,
            min: 1,
            max: 4,
            step: 1,
            unit: 'px',
        },
    ],
};

export const loadingButtonSettingsSchema: ComponentSettingsSchema = {
    componentId: 'loading-button',
    fields: [
        {
            id: 'text',
            type: 'text',
            label: 'Button Text',
            group: 'content',
            default: 'Submit',
            maxLength: 30,
        },
        {
            id: 'loadingText',
            type: 'text',
            label: 'Loading Text',
            group: 'content',
            default: 'Loading...',
            maxLength: 30,
        },
        {
            id: 'backgroundColor',
            type: 'color',
            label: 'Background Color',
            group: 'style',
            default: '#ffffff',
        },
        {
            id: 'textColor',
            type: 'color',
            label: 'Text Color',
            group: 'style',
            default: '#0a0a0a',
        },
        {
            id: 'spinnerColor',
            type: 'color',
            label: 'Spinner Color',
            group: 'style',
            default: '#0a0a0a',
            isPro: true,
        },
        {
            id: 'borderRadius',
            type: 'slider',
            label: 'Border Radius',
            group: 'style',
            default: 8,
            min: 0,
            max: 50,
            step: 2,
            unit: 'px',
        },
    ],
};
