import { ComponentSettingsSchema } from '@/lib/settings-types';

export const contentCardSettingsSchema: ComponentSettingsSchema = {
    componentId: 'content-card',
    fields: [
        // Content
        {
            id: 'title',
            type: 'text',
            label: 'Card Title',
            group: 'content',
            default: 'Card Title',
            maxLength: 50,
        },
        {
            id: 'description',
            type: 'textarea',
            label: 'Description',
            group: 'content',
            default: 'This is a brief description of the card content.',
            maxLength: 200,
        },
        {
            id: 'buttonText',
            type: 'text',
            label: 'Button Text',
            group: 'content',
            default: 'Learn More',
            maxLength: 20,
        },

        // Style
        {
            id: 'backgroundColor',
            type: 'color',
            label: 'Background Color',
            group: 'style',
            default: '#111111',
        },
        {
            id: 'titleColor',
            type: 'color',
            label: 'Title Color',
            group: 'style',
            default: '#ffffff',
        },
        {
            id: 'descriptionColor',
            type: 'color',
            label: 'Description Color',
            group: 'style',
            default: '#a1a1a1',
        },
        {
            id: 'borderColor',
            type: 'color',
            label: 'Border Color',
            group: 'style',
            default: '#262626',
        },
        {
            id: 'borderRadius',
            type: 'slider',
            label: 'Border Radius',
            group: 'style',
            default: 16,
            min: 0,
            max: 32,
            step: 4,
            unit: 'px',
        },
        {
            id: 'padding',
            type: 'slider',
            label: 'Padding',
            group: 'style',
            default: 20,
            min: 12,
            max: 32,
            step: 4,
            unit: 'px',
        },

        // Advanced
        {
            id: 'showButton',
            type: 'toggle',
            label: 'Show Button',
            group: 'advanced',
            default: true,
        },
        {
            id: 'showBorder',
            type: 'toggle',
            label: 'Show Border',
            group: 'advanced',
            default: true,
        },
        {
            id: 'hoverEffect',
            type: 'toggle',
            label: 'Hover Effect',
            description: 'Lift card on hover',
            group: 'advanced',
            default: true,
            isPro: true,
        },
    ],
};

export const statsCardSettingsSchema: ComponentSettingsSchema = {
    componentId: 'stats-card',
    fields: [
        {
            id: 'label',
            type: 'text',
            label: 'Label',
            group: 'content',
            default: 'Total Users',
            maxLength: 30,
        },
        {
            id: 'value',
            type: 'text',
            label: 'Value',
            group: 'content',
            default: '12,345',
            maxLength: 20,
        },
        {
            id: 'change',
            type: 'text',
            label: 'Change (optional)',
            description: 'e.g., +12% or -5%',
            group: 'content',
            default: '+12%',
            maxLength: 10,
        },
        {
            id: 'backgroundColor',
            type: 'color',
            label: 'Background Color',
            group: 'style',
            default: '#111111',
        },
        {
            id: 'valueColor',
            type: 'color',
            label: 'Value Color',
            group: 'style',
            default: '#ffffff',
        },
        {
            id: 'labelColor',
            type: 'color',
            label: 'Label Color',
            group: 'style',
            default: '#6b6b6b',
        },
        {
            id: 'positiveColor',
            type: 'color',
            label: 'Positive Change Color',
            group: 'style',
            default: '#22c55e',
        },
        {
            id: 'negativeColor',
            type: 'color',
            label: 'Negative Change Color',
            group: 'style',
            default: '#ef4444',
        },
        {
            id: 'borderRadius',
            type: 'slider',
            label: 'Border Radius',
            group: 'style',
            default: 12,
            min: 0,
            max: 24,
            step: 4,
            unit: 'px',
        },
    ],
};

export const imageCardSettingsSchema: ComponentSettingsSchema = {
    componentId: 'image-card',
    fields: [
        {
            id: 'title',
            type: 'text',
            label: 'Title',
            group: 'content',
            default: 'Image Title',
            maxLength: 50,
        },
        {
            id: 'subtitle',
            type: 'text',
            label: 'Subtitle',
            group: 'content',
            default: 'Subtitle text',
            maxLength: 50,
        },
        {
            id: 'imageHeight',
            type: 'slider',
            label: 'Image Height',
            group: 'style',
            default: 200,
            min: 100,
            max: 400,
            step: 20,
            unit: 'px',
        },
        {
            id: 'backgroundColor',
            type: 'color',
            label: 'Background Color',
            group: 'style',
            default: '#111111',
        },
        {
            id: 'textColor',
            type: 'color',
            label: 'Text Color',
            group: 'style',
            default: '#ffffff',
        },
        {
            id: 'borderRadius',
            type: 'slider',
            label: 'Border Radius',
            group: 'style',
            default: 16,
            min: 0,
            max: 32,
            step: 4,
            unit: 'px',
        },
        {
            id: 'showOverlay',
            type: 'toggle',
            label: 'Show Text Overlay',
            description: 'Display text over image',
            group: 'advanced',
            default: false,
        },
    ],
};
