import { ComponentSettingsSchema } from '@/lib/settings-types';

export const toastNotificationSettingsSchema: ComponentSettingsSchema = {
    componentId: 'toast-notification',
    fields: [
        // Content
        {
            id: 'message',
            type: 'text',
            label: 'Message',
            group: 'content',
            default: 'Operation completed successfully!',
            placeholder: 'Enter toast message...',
            maxLength: 100,
        },
        {
            id: 'type',
            type: 'select',
            label: 'Toast Type',
            description: 'Determines the icon and default color',
            group: 'content',
            default: 'success',
            options: [
                { value: 'success', label: '✓ Success' },
                { value: 'error', label: '✕ Error' },
                { value: 'warning', label: '⚠ Warning' },
                { value: 'info', label: 'ℹ Info' },
            ],
        },

        // Style
        {
            id: 'backgroundColor',
            type: 'color',
            label: 'Background Color',
            group: 'style',
            default: '#111111',
        },
        {
            id: 'textColor',
            type: 'color',
            label: 'Text Color',
            group: 'style',
            default: '#ffffff',
        },
        {
            id: 'borderRadius',
            type: 'slider',
            label: 'Border Radius',
            group: 'style',
            default: 12,
            min: 0,
            max: 24,
            step: 2,
            unit: 'px',
        },

        // Advanced
        {
            id: 'duration',
            type: 'slider',
            label: 'Duration',
            description: 'How long the toast stays visible',
            group: 'advanced',
            default: 3000,
            min: 1000,
            max: 10000,
            step: 500,
            unit: 'ms',
        },
        {
            id: 'position',
            type: 'select',
            label: 'Position',
            group: 'advanced',
            default: 'top-right',
            options: [
                { value: 'top-right', label: 'Top Right' },
                { value: 'top-left', label: 'Top Left' },
                { value: 'bottom-right', label: 'Bottom Right' },
                { value: 'bottom-left', label: 'Bottom Left' },
                { value: 'top-center', label: 'Top Center' },
                { value: 'bottom-center', label: 'Bottom Center' },
            ],
        },
        {
            id: 'showIcon',
            type: 'toggle',
            label: 'Show Icon',
            group: 'advanced',
            default: true,
        },
        {
            id: 'dismissible',
            type: 'toggle',
            label: 'Dismissible',
            description: 'Allow users to close the toast',
            group: 'advanced',
            default: true,
        },
    ],
};

export const loadingSpinnerSettingsSchema: ComponentSettingsSchema = {
    componentId: 'loading-spinner',
    fields: [
        {
            id: 'size',
            type: 'slider',
            label: 'Size',
            group: 'style',
            default: 40,
            min: 16,
            max: 80,
            step: 4,
            unit: 'px',
        },
        {
            id: 'color',
            type: 'color',
            label: 'Spinner Color',
            group: 'style',
            default: '#ffffff',
        },
        {
            id: 'trackColor',
            type: 'color',
            label: 'Track Color',
            group: 'style',
            default: '#262626',
        },
        {
            id: 'strokeWidth',
            type: 'slider',
            label: 'Stroke Width',
            group: 'style',
            default: 4,
            min: 2,
            max: 8,
            step: 1,
            unit: 'px',
        },
        {
            id: 'speed',
            type: 'slider',
            label: 'Animation Speed',
            group: 'advanced',
            default: 1000,
            min: 500,
            max: 2000,
            step: 100,
            unit: 'ms',
            isPro: true,
        },
    ],
};
