import { ComponentSettingsSchema } from '@/lib/settings-types';

export const textInputSettingsSchema: ComponentSettingsSchema = {
    componentId: 'text-input',
    fields: [
        // Content
        {
            id: 'label',
            type: 'text',
            label: 'Label',
            group: 'content',
            default: 'Email Address',
            placeholder: 'Enter label...',
            maxLength: 50,
        },
        {
            id: 'placeholder',
            type: 'text',
            label: 'Placeholder',
            group: 'content',
            default: 'Enter your email...',
            maxLength: 100,
        },
        {
            id: 'helperText',
            type: 'text',
            label: 'Helper Text',
            description: 'Optional hint below the input',
            group: 'content',
            default: '',
            maxLength: 100,
        },
        {
            id: 'errorMessage',
            type: 'text',
            label: 'Error Message',
            group: 'content',
            default: 'This field is required',
            maxLength: 100,
        },

        // Style
        {
            id: 'backgroundColor',
            type: 'color',
            label: 'Background Color',
            group: 'style',
            default: '#0a0a0a',
        },
        {
            id: 'textColor',
            type: 'color',
            label: 'Text Color',
            group: 'style',
            default: '#ffffff',
        },
        {
            id: 'borderColor',
            type: 'color',
            label: 'Border Color',
            group: 'style',
            default: '#262626',
        },
        {
            id: 'focusBorderColor',
            type: 'color',
            label: 'Focus Border Color',
            group: 'style',
            default: '#ffffff',
        },
        {
            id: 'borderRadius',
            type: 'slider',
            label: 'Border Radius',
            group: 'style',
            default: 8,
            min: 0,
            max: 24,
            step: 2,
            unit: 'px',
        },
        {
            id: 'height',
            type: 'slider',
            label: 'Input Height',
            group: 'style',
            default: 44,
            min: 36,
            max: 56,
            step: 4,
            unit: 'px',
        },

        // Advanced
        {
            id: 'required',
            type: 'toggle',
            label: 'Required Field',
            group: 'advanced',
            default: false,
        },
        {
            id: 'showLabel',
            type: 'toggle',
            label: 'Show Label',
            group: 'advanced',
            default: true,
        },
        {
            id: 'inputType',
            type: 'select',
            label: 'Input Type',
            group: 'advanced',
            default: 'text',
            options: [
                { value: 'text', label: 'Text' },
                { value: 'email', label: 'Email' },
                { value: 'password', label: 'Password' },
                { value: 'number', label: 'Number' },
                { value: 'tel', label: 'Phone' },
            ],
        },
    ],
};

export const searchInputSettingsSchema: ComponentSettingsSchema = {
    componentId: 'search-input',
    fields: [
        {
            id: 'placeholder',
            type: 'text',
            label: 'Placeholder',
            group: 'content',
            default: 'Search...',
            maxLength: 50,
        },
        {
            id: 'backgroundColor',
            type: 'color',
            label: 'Background Color',
            group: 'style',
            default: '#111111',
        },
        {
            id: 'textColor',
            type: 'color',
            label: 'Text Color',
            group: 'style',
            default: '#ffffff',
        },
        {
            id: 'iconColor',
            type: 'color',
            label: 'Icon Color',
            group: 'style',
            default: '#6b6b6b',
        },
        {
            id: 'borderRadius',
            type: 'slider',
            label: 'Border Radius',
            group: 'style',
            default: 12,
            min: 0,
            max: 50,
            step: 2,
            unit: 'px',
        },
        {
            id: 'showClearButton',
            type: 'toggle',
            label: 'Show Clear Button',
            group: 'advanced',
            default: true,
        },
    ],
};

export const dropdownSettingsSchema: ComponentSettingsSchema = {
    componentId: 'dropdown',
    fields: [
        {
            id: 'label',
            type: 'text',
            label: 'Label',
            group: 'content',
            default: 'Select Option',
            maxLength: 50,
        },
        {
            id: 'options',
            type: 'list',
            label: 'Options',
            description: 'Dropdown options',
            group: 'content',
            default: ['Option 1', 'Option 2', 'Option 3'],
            itemLabel: 'Option',
            minItems: 2,
            maxItems: 20,
        },
        {
            id: 'placeholder',
            type: 'text',
            label: 'Placeholder',
            group: 'content',
            default: 'Choose an option...',
            maxLength: 50,
        },
        {
            id: 'backgroundColor',
            type: 'color',
            label: 'Background Color',
            group: 'style',
            default: '#0a0a0a',
        },
        {
            id: 'textColor',
            type: 'color',
            label: 'Text Color',
            group: 'style',
            default: '#ffffff',
        },
        {
            id: 'borderRadius',
            type: 'slider',
            label: 'Border Radius',
            group: 'style',
            default: 8,
            min: 0,
            max: 24,
            step: 2,
            unit: 'px',
        },
    ],
};
