import { ComponentSettingsSchema } from '@/lib/settings-types';

export const tabBarSettingsSchema: ComponentSettingsSchema = {
    componentId: 'tab-bar',
    fields: [
        // Content
        {
            id: 'tabs',
            type: 'list',
            label: 'Tab Labels',
            description: 'Add, remove, or reorder tabs',
            group: 'content',
            default: ['Home', 'Profile', 'Settings'],
            itemLabel: 'Tab',
            minItems: 2,
            maxItems: 6,
        },
        {
            id: 'selectedIndex',
            type: 'slider',
            label: 'Default Selected Tab',
            description: 'Which tab is selected by default (1-based)',
            group: 'content',
            default: 1,
            min: 1,
            max: 6,
            step: 1,
        },

        // Style
        {
            id: 'backgroundColor',
            type: 'color',
            label: 'Background Color',
            group: 'style',
            default: '#111111',
        },
        {
            id: 'activeTabColor',
            type: 'color',
            label: 'Active Tab Color',
            group: 'style',
            default: '#ffffff',
        },
        {
            id: 'inactiveTabColor',
            type: 'color',
            label: 'Inactive Tab Color',
            group: 'style',
            default: '#6b6b6b',
        },
        {
            id: 'indicatorColor',
            type: 'color',
            label: 'Indicator Color',
            description: 'Color of the active tab indicator line',
            group: 'style',
            default: '#ffffff',
        },
        {
            id: 'tabHeight',
            type: 'slider',
            label: 'Tab Height',
            group: 'style',
            default: 48,
            min: 36,
            max: 64,
            step: 4,
            unit: 'px',
        },
        {
            id: 'borderRadius',
            type: 'slider',
            label: 'Border Radius',
            group: 'style',
            default: 0,
            min: 0,
            max: 24,
            step: 2,
            unit: 'px',
        },

        // Advanced
        {
            id: 'animationDuration',
            type: 'slider',
            label: 'Animation Duration',
            description: 'Duration of tab switch animation',
            group: 'advanced',
            default: 200,
            min: 0,
            max: 500,
            step: 50,
            unit: 'ms',
            isPro: true,
        },
        {
            id: 'showIndicator',
            type: 'toggle',
            label: 'Show Indicator Line',
            description: 'Display animated indicator under active tab',
            group: 'advanced',
            default: true,
        },
        {
            id: 'fullWidth',
            type: 'toggle',
            label: 'Full Width Tabs',
            description: 'Stretch tabs to fill container width',
            group: 'advanced',
            default: true,
        },
    ],
};

export const animatedUnderlineTabsSchema: ComponentSettingsSchema = {
    componentId: 'animated-underline-tabs',
    fields: [
        {
            id: 'tabs',
            type: 'list',
            label: 'Tab Labels',
            group: 'content',
            default: ['Overview', 'Features', 'Pricing'],
            itemLabel: 'Tab',
            minItems: 2,
            maxItems: 6,
        },
        {
            id: 'backgroundColor',
            type: 'color',
            label: 'Background Color',
            group: 'style',
            default: '#0a0a0a',
        },
        {
            id: 'activeColor',
            type: 'color',
            label: 'Active Tab Color',
            group: 'style',
            default: '#ffffff',
        },
        {
            id: 'inactiveColor',
            type: 'color',
            label: 'Inactive Tab Color',
            group: 'style',
            default: '#6b6b6b',
        },
        {
            id: 'underlineHeight',
            type: 'slider',
            label: 'Underline Height',
            group: 'style',
            default: 2,
            min: 1,
            max: 4,
            step: 1,
            unit: 'px',
        },
    ],
};
