-- =============================================
-- NEW BACKGROUNDS MIGRATION
-- Adds 25 new backgrounds to existing Supabase table
-- =============================================

-- 5 NEW GRADIENTS
INSERT INTO backgrounds (id, name, category, subcategory, description, svg_template, image_position, tags) VALUES
('grainy-purple', 'Grainy Purple', 'gradients', 'noise', 'Noisy purple gradient with film grain effect', '<svg xmlns=''http://www.w3.org/2000/svg'' width=''100%'' height=''100%'' viewBox=''0 0 400 400''><defs><filter id=''noise''><feTurbulence type=''fractalNoise'' baseFrequency=''0.65'' numOctaves=''3'' stitchTiles=''stitch''/></filter><linearGradient id=''grad'' x1=''0%'' y1=''0%'' x2=''100%'' y2=''100%''><stop offset=''0%'' stop-color=''{{primaryColor}}''/><stop offset=''100%'' stop-color=''{{secondaryColor}}''/></linearGradient></defs><rect width=''400'' height=''400'' fill=''url(#grad)''/><rect width=''400'' height=''400'' filter=''url(#noise)'' opacity=''0.15''/></svg>', 'Fill', ARRAY['grainy', 'noise', 'purple', 'texture']),

('holographic', 'Holographic', 'gradients', 'iridescent', 'Iridescent rainbow holographic effect', '<svg xmlns=''http://www.w3.org/2000/svg'' width=''100%'' height=''100%'' viewBox=''0 0 400 400''><defs><linearGradient id=''holo'' x1=''0%'' y1=''0%'' x2=''100%'' y2=''100%''><stop offset=''0%'' stop-color=''#FF6B6B''/><stop offset=''20%'' stop-color=''#FFE66D''/><stop offset=''40%'' stop-color=''#4ECDC4''/><stop offset=''60%'' stop-color=''#45B7D1''/><stop offset=''80%'' stop-color=''#96CEB4''/><stop offset=''100%'' stop-color=''#DDA0DD''/></linearGradient></defs><rect width=''400'' height=''400'' fill=''url(#holo)''/></svg>', 'Fill', ARRAY['holographic', 'rainbow', 'iridescent', 'colorful']),

('cosmic-dust', 'Cosmic Dust', 'gradients', 'space', 'Space nebula with cosmic dust particles', '<svg xmlns=''http://www.w3.org/2000/svg'' width=''100%'' height=''100%'' viewBox=''0 0 400 400''><defs><radialGradient id=''nebula'' cx=''30%'' cy=''30%'' r=''70%''><stop offset=''0%'' stop-color=''#7C3AED''/><stop offset=''50%'' stop-color=''#1E1B4B''/><stop offset=''100%'' stop-color=''#0F0F23''/></radialGradient></defs><rect width=''400'' height=''400'' fill=''url(#nebula)''/><circle cx=''50'' cy=''80'' r=''1'' fill=''white'' opacity=''0.8''/><circle cx=''150'' cy=''50'' r=''0.5'' fill=''white'' opacity=''0.6''/><circle cx=''300'' cy=''120'' r=''1.2'' fill=''white'' opacity=''0.9''/><circle cx=''350'' cy=''200'' r=''0.8'' fill=''white'' opacity=''0.7''/><circle cx=''80'' cy=''300'' r=''1'' fill=''white'' opacity=''0.5''/></svg>', 'Fill', ARRAY['cosmic', 'space', 'nebula', 'dark']),

('aurora-mesh', 'Aurora Mesh', 'gradients', 'mesh', 'Mixed aurora orbs with mesh effect', '<svg xmlns=''http://www.w3.org/2000/svg'' width=''100%'' height=''100%'' viewBox=''0 0 400 400''><defs><radialGradient id=''orb1'' cx=''20%'' cy=''30%'' r=''50%''><stop offset=''0%'' stop-color=''#22D3EE'' stop-opacity=''0.6''/><stop offset=''100%'' stop-color=''transparent''/></radialGradient><radialGradient id=''orb2'' cx=''80%'' cy=''70%'' r=''50%''><stop offset=''0%'' stop-color=''#A78BFA'' stop-opacity=''0.6''/><stop offset=''100%'' stop-color=''transparent''/></radialGradient><radialGradient id=''orb3'' cx=''60%'' cy=''20%'' r=''40%''><stop offset=''0%'' stop-color=''#34D399'' stop-opacity=''0.5''/><stop offset=''100%'' stop-color=''transparent''/></radialGradient></defs><rect width=''400'' height=''400'' fill=''#0F172A''/><rect width=''400'' height=''400'' fill=''url(#orb1)''/><rect width=''400'' height=''400'' fill=''url(#orb2)''/><rect width=''400'' height=''400'' fill=''url(#orb3)''/></svg>', 'Fill', ARRAY['aurora', 'mesh', 'orbs', 'colorful']),

('glass-tint', 'Glass Tint', 'gradients', 'glass', 'Glassmorphism-ready tinted background', '<svg xmlns=''http://www.w3.org/2000/svg'' width=''100%'' height=''100%'' viewBox=''0 0 400 400''><defs><linearGradient id=''glass'' x1=''0%'' y1=''0%'' x2=''100%'' y2=''100%''><stop offset=''0%'' stop-color=''{{primaryColor}}'' stop-opacity=''0.1''/><stop offset=''100%'' stop-color=''{{secondaryColor}}'' stop-opacity=''0.2''/></linearGradient></defs><rect width=''400'' height=''400'' fill=''url(#glass)''/></svg>', 'Fill', ARRAY['glass', 'tint', 'glassmorphism', 'subtle'])

ON CONFLICT (id) DO NOTHING;

-- 5 NEW PATTERNS
INSERT INTO backgrounds (id, name, category, subcategory, description, svg_template, image_position, tags) VALUES
('dot-matrix', 'Dot Matrix', 'patterns', 'dots', 'Regular dot matrix pattern', '<svg xmlns=''http://www.w3.org/2000/svg'' width=''16'' height=''16'' viewBox=''0 0 16 16''><circle cx=''8'' cy=''8'' r=''1'' fill=''{{primaryRgba}}''/></svg>', 'Tile', ARRAY['dots', 'matrix', 'grid', 'minimal']),

('double-diagonal', 'Double Diagonal', 'patterns', 'lines', 'Double diagonal crosshatch lines', '<svg xmlns=''http://www.w3.org/2000/svg'' width=''20'' height=''20'' viewBox=''0 0 20 20''><path d=''M0,0 L20,20 M20,0 L0,20'' stroke=''{{primaryRgba}}'' stroke-width=''0.5''/></svg>', 'Tile', ARRAY['diagonal', 'crosshatch', 'lines', 'geometric']),

('circuit-lines', 'Circuit Lines', 'patterns', 'tech', 'Tech circuit board lines', '<svg xmlns=''http://www.w3.org/2000/svg'' width=''50'' height=''50'' viewBox=''0 0 50 50''><path d=''M0,25 L15,25 L15,10 L35,10 L35,25 L50,25'' stroke=''{{primaryRgba}}'' stroke-width=''1'' fill=''none''/><circle cx=''15'' cy=''10'' r=''2'' fill=''{{primaryRgba}}''/><circle cx=''35'' cy=''10'' r=''2'' fill=''{{primaryRgba}}''/></svg>', 'Tile', ARRAY['circuit', 'tech', 'digital', 'lines']),

('contour-map', 'Contour Map', 'patterns', 'organic', 'Topographic contour lines', '<svg xmlns=''http://www.w3.org/2000/svg'' width=''100'' height=''100'' viewBox=''0 0 100 100''><ellipse cx=''50'' cy=''50'' rx=''45'' ry=''25'' stroke=''{{primaryRgba}}'' stroke-width=''0.5'' fill=''none''/><ellipse cx=''50'' cy=''50'' rx=''30'' ry=''15'' stroke=''{{primaryRgba}}'' stroke-width=''0.5'' fill=''none''/><ellipse cx=''50'' cy=''50'' rx=''15'' ry=''8'' stroke=''{{primaryRgba}}'' stroke-width=''0.5'' fill=''none''/></svg>', 'Tile', ARRAY['contour', 'map', 'topography', 'organic']),

('honeycomb-grid', 'Honeycomb Grid', 'patterns', 'geometric', 'Hexagonal honeycomb pattern', '<svg xmlns=''http://www.w3.org/2000/svg'' width=''30'' height=''52'' viewBox=''0 0 30 52''><path d=''M15,0 L30,8 L30,24 L15,32 L0,24 L0,8 Z M15,20 L30,28 L30,44 L15,52 L0,44 L0,28 Z'' stroke=''{{primaryRgba}}'' stroke-width=''0.5'' fill=''none''/></svg>', 'Tile', ARRAY['honeycomb', 'hexagon', 'grid', 'geometric'])

ON CONFLICT (id) DO NOTHING;

-- 5 NEW ANIMATED
INSERT INTO backgrounds (id, name, category, subcategory, description, svg_template, image_position, tags) VALUES
('floating-orbs', 'Floating Orbs', 'animated', 'premium', 'Slowly drifting colorful orbs', '<svg xmlns=''http://www.w3.org/2000/svg'' width=''100%'' height=''100%'' viewBox=''0 0 400 400''><circle cx=''100'' cy=''100'' r=''40'' fill=''{{primaryColor}}'' fill-opacity=''0.3''><animate attributeName=''cy'' values=''100;300;100'' dur=''8s'' repeatCount=''indefinite''/></circle><circle cx=''300'' cy=''250'' r=''30'' fill=''{{secondaryColor}}'' fill-opacity=''0.3''><animate attributeName=''cy'' values=''250;100;250'' dur=''6s'' repeatCount=''indefinite''/></circle><circle cx=''200'' cy=''350'' r=''50'' fill=''{{primaryColor}}'' fill-opacity=''0.2''><animate attributeName=''cx'' values=''200;300;200'' dur=''10s'' repeatCount=''indefinite''/></circle></svg>', 'Fill', ARRAY['floating', 'orbs', 'animated', 'soft']),

('expanding-rings', 'Expanding Rings', 'animated', 'premium', 'Expanding ripple ring effect', '<svg xmlns=''http://www.w3.org/2000/svg'' width=''100%'' height=''100%'' viewBox=''0 0 400 400''><circle cx=''200'' cy=''200'' r=''20'' fill=''none'' stroke=''{{primaryColor}}'' stroke-width=''2''><animate attributeName=''r'' values=''20;180;20'' dur=''4s'' repeatCount=''indefinite''/><animate attributeName=''opacity'' values=''1;0;1'' dur=''4s'' repeatCount=''indefinite''/></circle><circle cx=''200'' cy=''200'' r=''60'' fill=''none'' stroke=''{{primaryColor}}'' stroke-width=''2''><animate attributeName=''r'' values=''60;180;60'' dur=''4s'' begin=''1s'' repeatCount=''indefinite''/><animate attributeName=''opacity'' values=''1;0;1'' dur=''4s'' begin=''1s'' repeatCount=''indefinite''/></circle></svg>', 'Fill', ARRAY['rings', 'ripple', 'expanding', 'animated']),

('shimmer-effect', 'Shimmer Effect', 'animated', 'premium', 'Subtle shimmer wave animation', '<svg xmlns=''http://www.w3.org/2000/svg'' width=''100%'' height=''100%'' viewBox=''0 0 400 400''><defs><linearGradient id=''shimmer'' x1=''0%'' y1=''0%'' x2=''100%'' y2=''0%''><stop offset=''0%'' stop-color=''transparent''/><stop offset=''50%'' stop-color=''{{primaryColor}}'' stop-opacity=''0.3''/><stop offset=''100%'' stop-color=''transparent''/><animate attributeName=''x1'' values=''-100%;100%'' dur=''2s'' repeatCount=''indefinite''/><animate attributeName=''x2'' values=''0%;200%'' dur=''2s'' repeatCount=''indefinite''/></linearGradient></defs><rect width=''400'' height=''400'' fill=''url(#shimmer)''/></svg>', 'Fill', ARRAY['shimmer', 'wave', 'subtle', 'animated']),

('drifting-particles', 'Drifting Particles', 'animated', 'premium', 'Floating particle field animation', '<svg xmlns=''http://www.w3.org/2000/svg'' width=''120'' height=''120'' viewBox=''0 0 120 120''><circle cx=''20'' cy=''20'' r=''2'' fill=''{{primaryColor}}'' opacity=''0.5''><animate attributeName=''cy'' values=''20;100;20'' dur=''5s'' repeatCount=''indefinite''/></circle><circle cx=''60'' cy=''80'' r=''1.5'' fill=''{{primaryColor}}'' opacity=''0.4''><animate attributeName=''cy'' values=''80;10;80'' dur=''4s'' repeatCount=''indefinite''/></circle><circle cx=''100'' cy=''50'' r=''2'' fill=''{{secondaryColor}}'' opacity=''0.6''><animate attributeName=''cy'' values=''50;110;50'' dur=''6s'' repeatCount=''indefinite''/></circle></svg>', 'Tile', ARRAY['particles', 'drifting', 'floating', 'animated']),

('color-shift', 'Color Shift', 'animated', 'premium', 'Smooth color shifting gradient', '<svg xmlns=''http://www.w3.org/2000/svg'' width=''100%'' height=''100%'' viewBox=''0 0 400 400''><defs><linearGradient id=''shift'' x1=''0%'' y1=''0%'' x2=''100%'' y2=''100%''><stop offset=''0%'' stop-color=''{{primaryColor}}''><animate attributeName=''stop-color'' values=''{{primaryColor}};{{secondaryColor}};#06B6D4;{{primaryColor}}'' dur=''6s'' repeatCount=''indefinite''/></stop><stop offset=''100%'' stop-color=''{{secondaryColor}}''><animate attributeName=''stop-color'' values=''{{secondaryColor}};#06B6D4;{{primaryColor}};{{secondaryColor}}'' dur=''6s'' repeatCount=''indefinite''/></stop></linearGradient></defs><rect width=''400'' height=''400'' fill=''url(#shift)''/></svg>', 'Fill', ARRAY['color', 'shift', 'gradient', 'animated'])

ON CONFLICT (id) DO NOTHING;

-- 5 NEW TEXTURES
INSERT INTO backgrounds (id, name, category, subcategory, description, svg_template, image_position, tags) VALUES
('film-grain', 'Film Grain', 'textures', 'noise', 'Classic film grain noise effect', '<svg xmlns=''http://www.w3.org/2000/svg'' width=''80'' height=''80'' viewBox=''0 0 80 80''><filter id=''filmgrain''><feTurbulence type=''fractalNoise'' baseFrequency=''0.9'' numOctaves=''4'' stitchTiles=''stitch''/><feColorMatrix type=''saturate'' values=''0''/></filter><rect width=''80'' height=''80'' filter=''url(#filmgrain)'' opacity=''0.12''/></svg>', 'Tile', ARRAY['film', 'grain', 'noise', 'vintage']),

('cardboard', 'Cardboard', 'textures', 'organic', 'Cardboard paper texture', '<svg xmlns=''http://www.w3.org/2000/svg'' width=''60'' height=''60'' viewBox=''0 0 60 60''><filter id=''cardboard''><feTurbulence type=''fractalNoise'' baseFrequency=''0.05'' numOctaves=''4''/><feDiffuseLighting lighting-color=''#f5e6d3'' surfaceScale=''1.5''><feDistantLight azimuth=''45'' elevation=''55''/></feDiffuseLighting></filter><rect width=''60'' height=''60'' filter=''url(#cardboard)'' opacity=''0.08''/></svg>', 'Tile', ARRAY['cardboard', 'paper', 'organic', 'craft']),

('linen-cloth', 'Linen Cloth', 'textures', 'fabric', 'Fine linen fabric texture', '<svg xmlns=''http://www.w3.org/2000/svg'' width=''6'' height=''6'' viewBox=''0 0 6 6''><line x1=''0'' y1=''3'' x2=''6'' y2=''3'' stroke=''{{primaryRgba}}'' stroke-width=''0.3''/><line x1=''3'' y1=''0'' x2=''3'' y2=''6'' stroke=''{{primaryRgba}}'' stroke-width=''0.3''/></svg>', 'Tile', ARRAY['linen', 'cloth', 'fabric', 'subtle']),

('brushed-steel', 'Brushed Steel', 'textures', 'metal', 'Brushed steel metal surface', '<svg xmlns=''http://www.w3.org/2000/svg'' width=''60'' height=''3'' viewBox=''0 0 60 3''><line x1=''0'' y1=''1.5'' x2=''60'' y2=''1.5'' stroke=''{{primaryRgba}}'' stroke-width=''0.3''/></svg>', 'Tile', ARRAY['brushed', 'steel', 'metal', 'industrial']),

('rough-concrete', 'Rough Concrete', 'textures', 'industrial', 'Rough concrete surface texture', '<svg xmlns=''http://www.w3.org/2000/svg'' width=''80'' height=''80'' viewBox=''0 0 80 80''><filter id=''roughconcrete''><feTurbulence type=''fractalNoise'' baseFrequency=''0.08'' numOctaves=''4''/><feColorMatrix type=''saturate'' values=''0''/></filter><rect width=''80'' height=''80'' filter=''url(#roughconcrete)'' opacity=''0.1''/></svg>', 'Tile', ARRAY['concrete', 'rough', 'industrial', 'urban'])

ON CONFLICT (id) DO NOTHING;

-- 5 NEW SHAPES
INSERT INTO backgrounds (id, name, category, subcategory, description, svg_template, image_position, tags) VALUES
('blob-morph', 'Blob Morph', 'shapes', 'organic', 'Organic blob cluster shapes', '<svg xmlns=''http://www.w3.org/2000/svg'' viewBox=''0 0 400 400''><circle cx=''80'' cy=''80'' r=''60'' fill=''{{primaryColor}}'' fill-opacity=''0.25''/><circle cx=''320'' cy=''120'' r=''80'' fill=''{{secondaryColor}}'' fill-opacity=''0.2''/><circle cx=''200'' cy=''320'' r=''100'' fill=''{{primaryColor}}'' fill-opacity=''0.15''/><circle cx=''60'' cy=''280'' r=''50'' fill=''{{secondaryColor}}'' fill-opacity=''0.3''/></svg>', 'Fill', ARRAY['blob', 'organic', 'soft', 'circles']),

('triangle-mesh', 'Triangle Mesh', 'shapes', 'geometric', 'Geometric triangle tessellation', '<svg xmlns=''http://www.w3.org/2000/svg'' width=''60'' height=''52'' viewBox=''0 0 60 52''><polygon points=''30,0 60,52 0,52'' stroke=''{{primaryRgba}}'' stroke-width=''0.5'' fill=''none''/></svg>', 'Tile', ARRAY['triangles', 'mesh', 'geometric', 'tessellation']),

('wave-stack', 'Wave Stack', 'shapes', 'waves', 'Stacked wave layer lines', '<svg xmlns=''http://www.w3.org/2000/svg'' viewBox=''0 0 1440 320''><path fill=''{{primaryColor}}'' fill-opacity=''0.2'' d=''M0,160 Q360,80 720,160 T1440,160 L1440,320 L0,320 Z''/><path fill=''{{primaryColor}}'' fill-opacity=''0.3'' d=''M0,200 Q360,140 720,200 T1440,200 L1440,320 L0,320 Z''/><path fill=''{{primaryColor}}'' fill-opacity=''0.5'' d=''M0,250 Q360,200 720,250 T1440,250 L1440,320 L0,320 Z''/></svg>', 'Fill', ARRAY['waves', 'stack', 'layers', 'bottom']),

('corner-glow', 'Corner Glow', 'shapes', 'accent', 'Corner accent with glow effect', '<svg xmlns=''http://www.w3.org/2000/svg'' viewBox=''0 0 400 400''><defs><radialGradient id=''cornerglow'' cx=''0%'' cy=''0%'' r=''70%''><stop offset=''0%'' stop-color=''{{primaryColor}}'' stop-opacity=''0.4''/><stop offset=''100%'' stop-color=''transparent''/></radialGradient></defs><rect width=''400'' height=''400'' fill=''url(#cornerglow)''/></svg>', 'Fill', ARRAY['corner', 'glow', 'accent', 'subtle']),

('decorative-frame', 'Decorative Frame', 'shapes', 'border', 'Decorative border frame element', '<svg xmlns=''http://www.w3.org/2000/svg'' viewBox=''0 0 400 400''><rect x=''20'' y=''20'' width=''360'' height=''360'' stroke=''{{primaryColor}}'' stroke-width=''2'' fill=''none'' stroke-opacity=''0.2'' rx=''20''/><rect x=''40'' y=''40'' width=''320'' height=''320'' stroke=''{{primaryColor}}'' stroke-width=''1'' fill=''none'' stroke-opacity=''0.1'' rx=''16''/></svg>', 'Fill', ARRAY['frame', 'border', 'decorative', 'elegant'])

ON CONFLICT (id) DO NOTHING;

-- Verify count
-- SELECT COUNT(*) as total_backgrounds FROM backgrounds;
