import { FormTemplate } from "./form-types";

export const formTemplates: FormTemplate[] = [
    {
        id: "clean-card",
        name: "Clean Card Form",
        description: "A clean, minimal form with soft shadows and rounded corners",
        thumbnail: "card",
        defaultConfig: {
            title: "Contact Form",
            subtitle: "Fill out the form below to get in touch",
            submitButtonText: "Submit",
            cancelButtonText: "Cancel",
            width: 400,
        },
        defaultFields: [
            {
                id: "field_name",
                type: "text",
                label: "Full Name",
                controlName: "txtFullName",
                required: true,
                placeholder: "Enter your name",
            },
            {
                id: "field_email",
                type: "text",
                label: "Email Address",
                controlName: "txtEmail",
                required: true,
                placeholder: "you@example.com",
            },
            {
                id: "field_message",
                type: "text",
                label: "Message",
                controlName: "txtMessage",
                required: false,
                placeholder: "Your message...",
            },
        ],
    },
    {
        id: "employee-onboarding",
        name: "Employee Onboarding",
        description: "Comprehensive new hire paperwork form",
        thumbnail: "onboarding",
        defaultConfig: {
            title: "New Employee Onboarding",
            subtitle: "Welcome! Please complete this form to finalize your onboarding",
            submitButtonText: "Submit",
            cancelButtonText: "Save Draft",
            width: 420,
        },
        defaultFields: [
            {
                id: "field_fullname",
                type: "text",
                label: "Full Name",
                controlName: "txtFullName",
                required: true,
                placeholder: "Enter your full name",
            },
            {
                id: "field_email",
                type: "text",
                label: "Email Address",
                controlName: "txtEmail",
                required: true,
                placeholder: "name@company.com",
            },
            {
                id: "field_phone",
                type: "text",
                label: "Phone Number",
                controlName: "txtPhone",
                required: true,
                placeholder: "+1 (555) 000-0000",
            },
            {
                id: "field_startdate",
                type: "date",
                label: "Start Date",
                controlName: "dpStartDate",
                required: true,
            },
            {
                id: "field_department",
                type: "dropdown",
                label: "Department",
                controlName: "ddDepartment",
                required: true,
                options: [
                    { id: "1", label: "Engineering", value: "Engineering" },
                    { id: "2", label: "Marketing", value: "Marketing" },
                    { id: "3", label: "Sales", value: "Sales" },
                    { id: "4", label: "HR", value: "HR" },
                    { id: "5", label: "Finance", value: "Finance" },
                ],
            },
            {
                id: "field_position",
                type: "text",
                label: "Position/Role",
                controlName: "txtPosition",
                required: true,
                placeholder: "e.g., Software Engineer",
            },
            {
                id: "field_emptype",
                type: "dropdown",
                label: "Employment Type",
                controlName: "ddEmpType",
                required: true,
                options: [
                    { id: "1", label: "Full-time", value: "Full-time" },
                    { id: "2", label: "Part-time", value: "Part-time" },
                    { id: "3", label: "Contract", value: "Contract" },
                ],
            },
            {
                id: "field_emergencyname",
                type: "text",
                label: "Emergency Contact Name",
                controlName: "txtEmergencyName",
                required: true,
                placeholder: "Full name",
            },
            {
                id: "field_relationship",
                type: "text",
                label: "Relationship",
                controlName: "txtRelationship",
                required: true,
                placeholder: "e.g., Spouse, Parent",
            },
            {
                id: "field_emergencyphone",
                type: "text",
                label: "Emergency Phone",
                controlName: "txtEmergencyPhone",
                required: true,
                placeholder: "+1 (555) 000-0000",
            },
            {
                id: "field_handbook",
                type: "checkbox",
                label: "I have received the Employee Handbook",
                controlName: "chkHandbook",
                required: false,
                defaultValue: false,
            },
            {
                id: "field_itsetup",
                type: "checkbox",
                label: "I have completed IT setup",
                controlName: "chkITSetup",
                required: false,
                defaultValue: false,
            },
        ],
    },
];
