import { FormTemplate } from "./form-types";

export const formTemplates: FormTemplate[] = [
    {
        id: "clean-card",
        name: "Clean Card Form",
        description: "A clean, minimal form with soft shadows and rounded corners",
        thumbnail: "card",
        defaultConfig: {
            title: "Contact Form",
            subtitle: "Fill out the form below to get in touch",
            submitButtonText: "Submit",
            cancelButtonText: "Cancel",
            width: 400,
        },
        defaultFields: [
            {
                id: "field_name",
                type: "text",
                label: "Full Name",
                controlName: "txtFullName",
                required: true,
                placeholder: "Enter your name",
            },
            {
                id: "field_email",
                type: "text",
                label: "Email Address",
                controlName: "txtEmail",
                required: true,
                placeholder: "you@example.com",
            },
            {
                id: "field_message",
                type: "text",
                label: "Message",
                controlName: "txtMessage",
                required: false,
                placeholder: "Your message...",
            },
        ],
    },
    {
        id: "modern-minimal",
        name: "Modern Minimal",
        description: "Ultra-clean design with minimal styling",
        thumbnail: "minimal",
        defaultConfig: {
            title: "Quick Survey",
            subtitle: "Help us improve by answering a few questions",
            submitButtonText: "Send",
            cancelButtonText: "Skip",
            width: 380,
        },
        defaultFields: [
            {
                id: "field_rating",
                type: "dropdown",
                label: "How would you rate us?",
                controlName: "ddRating",
                required: true,
                options: [
                    { id: "1", label: "Excellent", value: "5" },
                    { id: "2", label: "Good", value: "4" },
                    { id: "3", label: "Average", value: "3" },
                    { id: "4", label: "Poor", value: "2" },
                ],
            },
            {
                id: "field_feedback",
                type: "text",
                label: "Additional Feedback",
                controlName: "txtFeedback",
                required: false,
                placeholder: "Tell us more...",
            },
            {
                id: "field_subscribe",
                type: "toggle",
                label: "Subscribe to updates",
                controlName: "tglSubscribe",
                required: false,
                defaultValue: true,
            },
        ],
    },
    {
        id: "dark-theme",
        name: "Dark Theme",
        description: "Sleek dark mode form for modern apps",
        thumbnail: "dark",
        defaultConfig: {
            title: "Login",
            subtitle: "Enter your credentials to continue",
            submitButtonText: "Sign In",
            cancelButtonText: "Forgot Password?",
            width: 360,
        },
        defaultFields: [
            {
                id: "field_username",
                type: "text",
                label: "Username",
                controlName: "txtUsername",
                required: true,
                placeholder: "Username or email",
            },
            {
                id: "field_password",
                type: "text",
                label: "Password",
                controlName: "txtPassword",
                required: true,
                placeholder: "••••••••",
            },
            {
                id: "field_remember",
                type: "checkbox",
                label: "Remember me",
                controlName: "chkRemember",
                required: false,
                defaultValue: false,
            },
        ],
    },
];
